apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginxABC
      image: nginxABC
      ports:
        - containerPort: 80
        
    - name: nginxXYZ
      image: nginxXYZ
      ports:
        - containerPort: 81
